remote_theme: pages-themes/slate@v0.2.0
plugins:
gem "github-pages", group: :jekyll_plugins
title: CSS final project
description: Website for the final project in computational social science 02467.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
